title: "田康辉 | Tian Kanghui"
description: "中山大学智能工程学院 | 计算机视觉 | 机器学习 | 机器人"
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false
author:
  name: "田康辉"
  email: "tiankh@mail2.sysu.edu.cn"
